name: "Create branch in origin from another branch"
description: "Create branch in origin from another branch"

inputs:
  token:
    description: "Personal access token (PAT) used to fetch the repository"
    required: false
    default: ${{ github.token }}

  repository:
    description: "Repository name with owner. For example, actions/checkout"
    required: false
    default: ${{ github.repository }}

  STAGE:
    description: "STAGE"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        repository: ${{ inputs.repository }}

    - shell: bash
      run: |
        # remove branch
        set -x
        set +e

        [ -z "${{ inputs.STAGE }}" ] && { echo "STAGE is required"; exit 1; }

        git push --delete origin env/${{ inputs.STAGE }}
        exit 0
