name: "Export vars to github context"
description: "Export vars to github context"

inputs:
  data:
    description: "environment variables to be added MY_ENV=$(getEnv PROP_NAME)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache params
      uses: actions/cache@v3
      with:
        path: params_cache
        key: ${{ github.run_id }}

    - shell: bash
      run: |
        # export vars

        shopt -s expand_aliases
        alias getEnv=/opt/utils/feature_env/functions/getEnv.js

        set -x
        echo "
        ${{ inputs.data }}
        " | grep -ve '^$' >> $GITHUB_ENV

        exit 0
