name: "Export vars to github context"
description: "Export vars to github context"

inputs:
  data:
    description: "environment variables to be added MY_ENV=$(getEnv PROP_NAME)"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # export vars

        shopt -s expand_aliases
        alias getEnv=/opt/utils/feature_env/functions/getEnv.sh

        echo "
        ${{ inputs.data }}
        " | grep -ve '^$' >> $GITHUB_ENV
