name: "Register dns"
description: "Register dns entry in CF"

inputs:
  APPNAME:
    description: "APPNAME"
    required: true
  GROUP:
    description: "GROUP"
    required: true
  BRANCH:
    description: "BRANCH"
    required: true
  STAGE:
    description: "STAGE"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache params
      uses: actions/cache@v3
      with:
        path: /$GITHUB_WORKSPACE/$GITHUB_REPOSITORY/params_cache
        key: ${{ github.run_id }}

    - shell: bash
      run: |
        # register dns CNAME entry

        export APPNAME=${{ inputs.APPNAME }}
        export GROUP=${{ inputs.GROUP }}
        export BRANCH=${{ inputs.BRANCH }}
        export STAGE=${{ inputs.STAGE }}

        /opt/utils/feature_env/functions/registerDNS.sh
